import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
If you want to view the source, see the RecallKit Obsidian plugin source files.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [
		{
			name: "pdfjs-worker-inline",
			setup(build) {
				build.onResolve({ filter: /^pdfjs-worker$/ }, () => ({
					path: "pdfjs-worker",
					namespace: "pdfjs-worker",
				}));

				build.onLoad({ filter: /.*/, namespace: "pdfjs-worker" }, () => {
					const workerSource = readFileSync(
						join("node_modules", "pdfjs-dist", "legacy", "build", "pdf.worker.min.mjs"),
						"utf8",
					);

					return {
						contents: `export default ${JSON.stringify(workerSource)};`,
						loader: "js",
					};
				});
			},
		},
	],
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
